### PR TITLE
Minor code cleanup

### PR DESCRIPTION
**Pull request by sebthom**
I fixed a few compiler warnings. The code changes do not alter the runtime behavior of the code base.

### CODE REVIEW

**Comment by sebthom** [comment]
@vietj would you mind reviewing this PR? Thanks in advance!

**Comment by sebthom** [comment]
@cescoffier @vietj would you mind reviewing this PR? Thanks in advance!

**Comment by sebthom** [comment]
@cescoffier @vietj would you mind reviewing this PR? Thanks in advance!

**Comment by cescoffier** [comment]
Some of the code you changed is generated (the converters) - so it will be erased during the build.

**Comment by sebthom** [comment]
@cescoffier I removed the changes to generated classes

**Pull request closed without merging**
