### PR TITLE
ensure transport is disconnected on connection close, and respond to remote close frame

### PR DESCRIPTION
**Pull request by gemmellr**
The client doesn't disconnect the TCP connection on closure after receiving an AMQP Close frame, so if the other side doesn't either it will remain open. This is true of local and remote initiated closures. For remote closures, the client should additionally 'respond' first by sending its own Close frame as the protocol is symmetric and peers may or may not wait for the matched frame.

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
Thanks!

**Comment by cescoffier** [comment]
This should be backported in the 3.9 branch.

**Comment by gemmellr** [comment]
Backported in https://github.com/vert-x3/vertx-amqp-client/commit/9359789f59091ed4a186d58b0007df4bb6c97d77

**Comment by cescoffier** [comment]
Thanks @gemmellr !

**Pull request merged**
