### PR TITLE
test improvements

### PR DESCRIPTION
**Pull request by gemmellr**
Many of the tests use a full broker, e.g sending and receiving messages through the broker in attempt to verify some sender or receiver behaviour. Some of the tests on the other hand make use of a vertx-proton based server tailored to the specific behaviour under test. The latter approach tends to make for better tests, as they can more specifically and fully verify the client behaviour than is possible by observing either side of a broker intermediary. As a bonus they also tend to be faster as result of being simpler and having less moving parts.

This PR converts a few of the test classes (as a starting point, many more can be done) to use a vertx-proton based test server rather than a broker, maintaining the existing verifications and occasionally adding more (e.g verifying proper acknowledgement of received messages, the expected type of disposition was sent etc)

### CODE REVIEW

**Review by cescoffier — APPROVED** [review]
LGTM! 

Thanks!

**Comment by cescoffier** [comment]
@gemmellr do you think we should backport it to 3.9 too?

**Comment by gemmellr** [comment]
Probably yes, since its better/faster and will ease other backports to keep things closer. I didnt look into doing that yet though but I will.

**Comment by gemmellr** [comment]
Cherry picked to 3.9 in https://github.com/vert-x3/vertx-amqp-client/commit/cf66a30faf10dfeb3703133a6e56b095503e673c

**Comment by gemmellr** [comment]
Cherry picked to 3.9 in https://github.com/vert-x3/vertx-amqp-client/commit/cf66a30faf10dfeb3703133a6e56b095503e673c

**Comment by cescoffier** [comment]
Thanks @gemmellr

**Pull request merged**
