### PR TITLE
Fix not to lose messages while handling message and executing a scheduled message delivery async event

### LINKED ISSUE #36: handleMessage method polls buffered message without using it
```
  private void handleMessage(AmqpMessageImpl message) {
    boolean schedule = false;
    boolean dispatchNow = false;

    synchronized (this) {
      if (handler != null && demand > 0L && buffered.isEmpty()) {
        if (demand != Long.MAX_VALUE) {
          demand--;
        }
        dispatchNow = true;
      } else if (handler != null && demand > 0L) {
        // Buffered messages present, deliver the oldest of those instead
        buffered.add(message);
        message = buffered.poll();
        if (demand != Long.MAX_VALUE) {
          demand--;
        }

        // Schedule a delivery for the next buffered message
        schedule = true;
      } else {
        // Buffer message until we aren't paused
        buffered.add(message);
      }
    }

    // schedule next delivery if appropriate, after earlier delivery to allow chance to pause etc.
    if (schedule) {
      scheduleBufferedMessageDelivery();
    } else if (dispatchNow) {
      deliverMessageToHandler(message);
    }
  }
```

Version: 3.9.1

In AmqpReceiverImpl.handleMessage implementation above, when following conditions hold, the oldest message in the buffer is removed without using it.
- `!buffered.isEmpty()`
- `demand > 0`
- `handler != null`

Looks like issue can be fixed with either of the following
- Dispatching message immediately to the handler by setting dispatchNow flag instead of schedule flag
- Scheduling delivery for the next buffered message by setting schedule flag without removing the oldest buffered message and updating demand variable

Probably the preferred way would be dispatching the message immediately as there is no need to wait for dispatching the message later.

### LINKED ISSUE #37: Message lost
In some case a message can be lost, see https://github.com/vert-x3/vertx-amqp-client/commit/f6fd04b1167decf18802c04ffdb1f0c7275d7eb5

### LINKED ISSUE #38: scheduleBufferedMessageDelivery decrements the demand without delivering a message
```
private void scheduleBufferedMessageDelivery() {
    boolean schedule;

    synchronized (this) {
      schedule = !buffered.isEmpty() && demand > 0L;
    }

    if (schedule) {
      connection.runOnContext(v -> {
        AmqpMessageImpl message = null;

        synchronized (this) {
          if (demand > 0L) {
            if (demand != Long.MAX_VALUE) {
              demand--;
            }
            message = buffered.poll();
          }
        }

        if (message != null) {
          // Delivering outside the synchronized block
          deliverMessageToHandler(message);

          // Schedule a delivery for a further buffered message if any
          scheduleBufferedMessageDelivery();
        }
      });
    }
  }
```

Version: 3.9.1

scheduleBufferedMessageDelivery registers an async event to deliver messages to the handler, however, in a scenario where buffer is empty and there is a demand greater than 0, demand is still decremented even though there is no actual message delivered to the handler as message is set to null in this case.

At first glance, one might think that async event will not be scheduled if the buffer is empty, however there is no guarantee the condition to schedule message delivery will hold at the time of async event execution. There are multiple callers of scheduleBufferedMessageDelivery method so that multiple async events for message delivery can be scheduled at the same time. Fetch, handleMessage, handler and scheduleBufferedMessageDelivery itself are all calling scheduleBufferedMessageDelivery method.

In the scenario below, demand is decremented incorrectly and that stops message delivery from the AmqpReceiver buffer to the handlers.

  * There are two async events scheduled by scheduleBufferedMessageDelivery method
  * There is one message in the buffer and demand is set to 1
  * First async event gets triggered, while executing the async event, the only message in the buffer gets removed from the buffer and delivered to the handler and demand gets decremented to 0
  * Demand is incremented (after a fetch call as handler execution is complete)
  * Second async event gets triggered, while executing the async event, message retrieved from the buffer is null and demand gets decremented to 0
  * Second async event execution removes the demand incorrectly without delivering a message to the handler

This issue may cause stopping the delivery of the messsages to the handler forever.

When there is no actual message retrieved from the buffer, demand should not be decremented as demand is not met with a message delivery to the handler.

### PR DESCRIPTION
**Pull request by ferhatsahinkaya**
Fix not to lose messages while handling message and executing a scheduled message delivery async event

Do not decrement demand in scheduleBufferedMessageDelivery method when there is no message in the buffer
Deliver message to the handler immediately in handleMessage method when there is demand and buffer is not empty

Motivation:

This commit fixes #36, fixes #37 and fixes #38. We faced with these issues in our production environment. Occasionally, our amqp consumers stop consuming messages due to issue #38 so that we need to restart our pods having the issue in order to start consuming messages again. When demand is decremented incorrectly due to issue #38, there is no chance to recover as already placed demand is lost. After understanding how AmqpReceiver works and finding a solution to our problem, I have realised there is a chance to lose messages due to issues #36 and #37.

A new ReceiverTest is added as part of the commit. As all issues regarding the fix are caused due to race conditions and existing tests are integration tests rather than unit tests, in order to keep the consistency in the code base, I’ve added a new similar integration test to ReceiverTest class. 

The aim of the new test is to catch the cases below:
receiving message from ProtonReceiver (handleMessage method) when there are already messages in the buffer and demand is greater than zero
having buffer empty during execution of the async event scheduled in scheduleMessageDelivery method

In order to catch these cases, I sent two 1K batches to the broker and in between batches, I increased the demand to catch the above cases. However, technically, due to the existing testing style (integration testing receier with the broker) and limited accessibility to the internals of the AmqpReceiver, added test only increases the chances of the failure but doesn’t guarantee hitting the cases in the issues as there is no easy way to control the thread scheduling to process asynch events for dispatching messages to handlers or fetching messages from broker to the buffer. Please feel free to reach out to me in case of any concern. 

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by vietj** [comment]
can you review this one @cescoffier ?

**Review by cescoffier — APPROVED** [review]

**Comment by cescoffier** [comment]
This would need to be backported to 3.9.2.

**Comment by ferhatsahinkaya** [comment]
@cescoffier thanks for the review. Do I need to do anything else to get the fix merged with 3.9 and master branches? Unfortunately, couldn't see any clear process to follow.

**Comment by cescoffier** [comment]
@ferhatsahinkaya I will do it, that's a reminder for me.

**Comment by cescoffier** [comment]
@vietj - Backport done in the 3.9 branch.

**Comment by vietj** [comment]
thanks

**Pull request merged**
